version: '3'

# ---
#  Startet alle externen Services, die für den lokalen Betrieb der Lunchbox
#  via "gradle bootRun" notwendig sind.
# ---
services:
  # ---
  # OCR service
  # ---
  ocr:
    image: docker.rori.dev/lunchbox-service-ocr
    ports:
      - "9292:9292"


  # ---
  # rendertron
  # ---
  rendertron:
    image: ammobindotca/rendertron
    environment:
      - PORT=3005
    ports:
      - "3005:3005"
