stages:
  - build
  - deploy

build_frontend-web-vue:
  stage: build
  trigger:
    include: frontend-web-vue/.gitlab-ci.yml
    strategy: depend

build_backend-spring-kotlin:
  stage: build
  trigger:
    include: backend-spring-kotlin/.gitlab-ci.yml
    strategy: depend

deploy:
  stage: deploy
  trigger:
    include: app/.gitlab-ci.yml
    strategy: depend
  only:
    - master
