services:
  frontend-v1:
    image: docker.rori.dev/lunchbox-frontend:1.0
    networks:
      webgateway:
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.lunchbox-frontend-v1.rule: Host(`lunchbox.${BASE_DOMAIN}`)
      traefik.http.routers.lunchbox-frontend-v1.entrypoints: web

  frontend-v2:
    image: docker.rori.dev/lunchbox-frontend:latest
    networks:
      webgateway:
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.lunchbox-frontend-v2.rule: Host(`lunchbox2.${BASE_DOMAIN}`)
      traefik.http.routers.lunchbox-frontend-v2.entrypoints: web

  backend:
    image: docker.rori.dev/lunchbox-backend:latest
    depends_on:
      - ocr
      - rendertron
    networks:
      webgateway:
      default:
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.lunchbox-backend.rule: (Host(`lunchbox.${BASE_DOMAIN}`) || Host(`lunchbox2.${BASE_DOMAIN}`)) && (PathPrefix(`/api`) || PathPrefix(`/feed`))
      traefik.http.routers.lunchbox-backend.entrypoints: web
      traefik.http.services.lunchbox-backend.loadbalancer.server.port: 8080
      # Die Android-App nutzt noch HTTP und kann mit Redirects nicht um
      traefik.http.routers.lunchbox-backend-web80.rule: (Host(`lunchbox.${BASE_DOMAIN}`) || Host(`lunchbox2.${BASE_DOMAIN}`)) && (PathPrefix(`/api`) || PathPrefix(`/feed`))
      traefik.http.routers.lunchbox-backend-web80.entrypoints: web80

  # ---
  #  OCR service
  # ---
  ocr:
    image: docker.rori.dev/lunchbox-service-ocr:latest
    environment:
      - PORT=9292
    restart: unless-stopped
    networks:
      default:


  # ---
  #  Rendertron
  # ---
  rendertron:
    image: ammobindotca/rendertron
    environment:
      - PORT=3005
    restart: unless-stopped
    networks:
      default:


networks:
  webgateway:
    external: true
